<?php

try {
    $p = new PDFlib();

    /*  open new PDF file; insert a file name to create the PDF on disk */
    if ($p->begin_document("", "") == 0) {
        die("Error: " . $p->get_errmsg());
    }

    $p->set_info("Creator", "hello.php");
    $p->set_info("Author", "MaskaEvid 1.1 by Martin Skarecky");
    $p->set_info("Title", "Predavaci protokol");
	
	
    $p->begin_page_ext(595, 842, "");

	//$p->moveto(1,1);
	//$p->rect(100,100,50,50);
    
	$cislo="53355";
	
	$font2 = $p->load_font("Times-Roman","cp1250","");	
	$p->setfont($font2, 10.0);
	$p->set_text_pos(400,810);
	$p->show("Generated by maskaEvid 1.1");
	$p->continue_text("Èíslo evidenèního archu:".$cislo);


    $font = $p->load_font("Helvetica", "cp1250", "");
    
    $p->setfont($font, 12.0);
    $p->set_text_pos(50, 700);
    $p->show("============");
    $p->continue_text("Protokol o pøedání");
    $p->continue_text("------------------");
    $p->continue_text("øèšìáížèážìéíáøìéíšáøìšéøáìé");
    
	
	
	$p->save();
	$p->translate(200, 100); /* move origin to corner of rectangle*/
	//$p->rotate(45.0); /* rotate coordinates */
	$p->rect(0.0, 0.0, 75.0, 25.0); /* draw rotated rectangle */
	$p->stroke();
	$p->restore();
	
	
	
	
	$p->set_parameter("SearchPath", "/var/www/html");
	$p->set_parameter("FontOutline", "f1=cour.ttf");
	$font3 = $p->load_font("f1", "cp1250", "");
	$p->setfont($font3, 12.0);
	$p->set_text_pos(50,500);
	$p->show("25389ìíøáìšéšøžéìýéø+ìšáéìýžìéýžìéøìšéáìéèáìšéèá");
	
	
	
	$p->end_page_ext("");
	
	$p->end_document("");

    $buf = $p->get_buffer();
    $len = strlen($buf);

    header("Content-type: application/pdf");
    header("Content-Length: $len");
    header("Content-Disposition: inline; filename=hello.pdf");
    print $buf;
}
catch (PDFlibException $e) {
    die("PDFlib exception occurred in hello sample:\n" .
    "[" . $e->get_errnum() . "] " . $e->get_apiname() . ": " .
    $e->get_errmsg() . "\n");
}
catch (Exception $e) {
    die($e);
}
$p = 0;

?>

